version: '3.3'

services:

    gousers:
        build:
            context: .
            dockerfile: ./Dockerfile
        ports:
            - "8080:8080"
        networks:
            - frontend

networks:
    frontend:
